pipeline {
    agent any

    parameters {
        string(
            name: 'APP_PORT',
            defaultValue: '3000',
            description: 'Server Port'
        )
    }

    environment {
        IMAGE_NAME = "jenkins-demo-app"
        // NodeJS aur Docker dono ke paths
        PATH = "C:\\Program Files\\nodejs;C:\\Program Files\\Docker\\Docker\\resources\\bin;%PATH%"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code from git repo'
                checkout scm
            }
        }
        stage('Check Docker') {
            steps {
                bat 'docker --version'
            }
        }
        stage('Dependencies') {
            steps {
                bat 'cd JenkinsFileDemo && npm install'
            }
        }
        stage('Test App') {
            steps {
                bat 'cd JenkinsFileDemo && npm test'
            }
        }
        stage('Build') {
            steps {
                bat 'cd JenkinsFileDemo && docker build -t %IMAGE_NAME%:%BUILD_NUMBER% .'
            }
        }
        stage('Run Container') {
            steps {
                bat '''
                    docker run -d --name node-app-%BUILD_NUMBER% -p %APP_PORT%:3000 %IMAGE_NAME%:%BUILD_NUMBER%
                '''
            }
        }
        stage('Verify') {
            steps {
                bat '''
                    echo App deployed successfully
                    echo Open http://localhost:%APP_PORT%
                    docker ps
                '''
            }
        }
    }   
}